

version: '3'

services:
  api:
    container_name: wongames_api
    image: eduhdev/wongames-api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'sk_test_51LfmJaCaLj3dHMgdfQQQf0jtp2iHsK4FxBHxwCVRwIJbvSqr4n68cnxbEnspshlDWAfffV1og1YWRpQ0kw2AC8uW00MHCAO8bA'
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: eduhdev/wongames-db:latest
    ports:
      - '5432:5432'